main: me.mattyhd0.chatcolor.ChatColor
name: 'ChatColor'
version: '${project.version}' #Added %chatcolor_last_message%
api-version: 1.13
description: 'A plugin that allows you to create color patterns for the chat'
author: MattyHD0
softdepend: [PlaceholderAPI]
commands:
  chatcolor:
    description: ChatColor main command
    usage: /<command>
  chatcoloradmin:
    description: ChatColor admin command
    usage: /<command>